/*
 * URL of the live JSON file generated by the mod jc_special.
 */
const SERVER_JSON_URL = "https://game.dssapp.us/justcraft/server.json";

/*
 * URL of the places JSON file generated by the mod jc_welcome.
 */
const PLACES_JSON_URL = "https://game.dssapp.us/justcraft/places.json";

/*
 * URL of the rules JSON file generated by the mod jc_welcome.
 */
const RULES_JSON_URL = "https://game.dssapp.us/justcraft/rules.json";

/*
 * Website translations.
 *
 * For now, we use hard coded words until I figure out
 * a better way to offer a translated website with
 * GitHub hosting.
 *
 * English is the fallback language.
 */
const translations = {
  en: {
    pageTitle: "Just-Craft Adventure | Official Server",
    serverTitle: "JUST-CRAFT ADVENTURE SERVER",
    officialCommunity: "Official Community",
    joinDiscord: "Join our Discord!",
    joinLink: "JOIN",
    officialForum: "Luanti Forum",
    visitForum: "Just-Craft Forum Post",
    visitLink: "VISIT",
    liveServerStatus: "LIVE SERVER STATUS",
    checkingServer: "Checking server...",
    serverOnline: "SERVER ONLINE",
    serverStatusUnavailable: "SERVER STATUS UNAVAILABLE",
    playersOnline: "PLAYERS ONLINE",
    totalMods: "TOTAL NUMBER OF MODS",
    luantiVersion: "LUANTI VERSION",
    onlinePlayers: "ONLINE PLAYERS",
    checkingPlayers: "Checking players...",
    nobodyOnline: "Nobody is currently online.",
    serverPlaces: "SERVER PLACES",
    loadingRules: "Loading server rules...",
    serverRulesTitle: "SERVER RULES",
    noRules: "No server rules are currently available.",
    couldNotContact: "Could not contact the server.",
    serverDataUpdated: "Server data updated: ",
    footerPowered: "Powered by Luanti."
  },

  es: {
    pageTitle: "Just-Craft Adventure | Servidor Oficial",
    serverTitle: "SERVIDOR JUST-CRAFT ADVENTURE",
    officialCommunity: "Comunidad Oficial",
    joinDiscord: "¡Únete a nuestro Discord!",
    joinLink: "UNIRSE",
    officialForum: "Foro de Luanti",
    visitForum: "Publicación del foro de Just-Craft",
    visitLink: "VISITAR",
    liveServerStatus: "ESTADO DEL SERVIDOR EN VIVO",
    checkingServer: "Comprobando servidor...",
    serverOnline: "SERVIDOR EN LÍNEA",
    serverStatusUnavailable: "ESTADO DEL SERVIDOR NO DISPONIBLE",
    playersOnline: "JUGADORES EN LÍNEA",
    totalMods: "NÚMERO TOTAL DE MODS",
    luantiVersion: "VERSIÓN DE LUANTI",
    onlinePlayers: "JUGADORES EN LÍNEA",
    checkingPlayers: "Comprobando jugadores...",
    nobodyOnline: "Nadie está conectado actualmente.",
    serverPlaces: "LUGARES DEL SERVIDOR",
    serverRulesTitle: "REGLAS DEL SERVIDOR",
    loadingRules: "Cargando las reglas del servidor...",
    noRules: "No hay reglas del servidor disponibles actualmente.",
    couldNotContact: "No se pudo contactar con el servidor.",
    serverDataUpdated: "Datos del servidor actualizados: ",
    footerPowered: "Desarrollado con Luanti."
  }
};

/*
 * Detect visitor language.
 *
 * Spanish browsers use Spanish.
 * Everything else uses English.
 */
const browserLanguage = navigator.language.toLowerCase();

const currentLanguage = browserLanguage.startsWith("es") ? "es" : "en";
// const currentLanguage = "es";

/*
 * Set the HTML language.
 */
document.documentElement.lang = currentLanguage;

const T = translations[currentLanguage];

/*
 * Apply website translations.
 */
function applyTranslations(){
  document.title = T.pageTitle;

  document.getElementById("serverTitle").textContent = T.serverTitle;

  document.getElementById("officialCommunity").textContent = T.officialCommunity;
  document.getElementById("joinDiscord").textContent = T.joinDiscord;
  document.getElementById("joinLink").textContent = T.joinLink;

  document.getElementById("officialForum").textContent = T.officialForum;
  document.getElementById("visitForum").textContent = T.visitForum;
  document.getElementById("visitLink").textContent = T.visitLink;

  document.getElementById("liveServerStatus").textContent = T.liveServerStatus;

  document.getElementById("playersOnlineLabel").textContent = T.playersOnline;
  document.getElementById("totalModsLabel").textContent = T.totalMods;
  document.getElementById("luantiVersionLabel").textContent = T.luantiVersion;

  document.getElementById("onlinePlayersTitle").textContent = T.onlinePlayers;
  document.getElementById("serverPlacesTitle").textContent = T.serverPlaces;

  document.getElementById("serverRulesTitle").textContent = T.serverRulesTitle;

  document.getElementById("loadingRules").textContent = T.loadingRules;

  document.getElementById("footerPowered").textContent = T.footerPowered;
}

/*
 * Load static data
 */
let placesData = null;
let rulesData = null;

async function loadStaticData(){
  const responsePlaces = await fetch(PLACES_JSON_URL + "?t=" + Date.now(), { cache: "no-cache" } );

  if(!responsePlaces.ok){
    throw new Error("HTTP error: " + responsePlaces.status);
  }

  placesData = await responsePlaces.json();

  const responseRules = await fetch(RULES_JSON_URL + "?t=" + Date.now(), { cache: "no-cache" } );

  if(!responseRules.ok){
    throw new Error("HTTP error: " + responseRules.status);
  }

  rulesData = await responseRules.json();
}

/*
 * Load server information.
 */
async function loadServerData(){
  try{
    /*
     * Add a timestamp to prevent browser caching.
     */
    const responseServer = await fetch(SERVER_JSON_URL + "?t=" + Date.now(), { cache: "no-store" } );
    if(!responseServer.ok){
      throw new Error( "HTTP error: " + responseServer.status );
    }
    const dataServer = await responseServer.json();

    /*
     * Server is online.
     */
    document.getElementById("statusDot").className = "status-dot online";
    document.getElementById("serverStatus").textContent = T.serverOnline;

    /*
     * Player counts.
     */
    document.getElementById("onlinePlayers").textContent = dataServer.players.online;

    /*
     * Mod counts.
     */
    document.getElementById("totalModCount").textContent = dataServer.server.mods.toLocaleString();

    /*
     * Luanti version.
     */

    document.getElementById("luantiVersion").textContent = dataServer.server.luanti_version;

    /*
     * Online player names.
     */
    const playerList = document.getElementById("playerList");
    playerList.innerHTML = "";

    if(dataServer.players.online_names && dataServer.players.online_names.length > 0){
      dataServer.players.online_names.forEach(
        function(playerName){
          const player = document.createElement("span");
          player.className = "player-name";
          player.textContent = playerName;
          playerList.appendChild(player);
        }
      );
    }else{
      playerList.innerHTML = '<span class="no-players">' + T.nobodyOnline + '</span>';
    }

    /*
     * Server places.
     */
    const placesList = document.getElementById("placesList");
    placesList.innerHTML = "";
    if(placesData.places){
      placesData.places.forEach(
        function(place){
          const card = document.createElement("div");
          card.className = "place-card";

          card.innerHTML =
            '<div class="place-name">' +
              place.label +
            '</div>' +
            '<div class="place-command">' +
              '/' +
              place.name +
            '</div>' +
            '<div class="place-coordinates">' +
              '(' + place.x + ',' + place.y + ',' + place.z + ')' +
            '</div>'  +
            '';
          placesList.appendChild(card);
        }
      );
    }

    /*
     * Server rules.
     */
    // const rules = currentLanguage === "es" ? rulesData.rules_es : rulesData.rules;
    const rules = (currentLanguage === "es")
      ? (rulesData.rules_es ? rulesData.rules_es : rulesData.rules)
      : (rulesData.rules ? rulesData.rules : null);

    const rulesList = document.getElementById("rulesList");
    rulesList.innerHTML = "";

    if(rules && rules.length > 0){
      rules.forEach(
        function(rule, index){
          const ruleItem = document.createElement("div");
          ruleItem.className = "rule-item";

          const ruleNumber = document.createElement("span");
          ruleNumber.className = "rule-number";
          ruleNumber.textContent = (index + 1) + ")";

          ruleItem.appendChild(ruleNumber);
          ruleItem.appendChild(document.createTextNode(rule));

          rulesList.appendChild(ruleItem);
        }
      );

    }else{
      rulesList.innerHTML = '<div class="no-players">' + T.noRules + '</div>';
    }

    /*
     * Last update time.
     */
    const updatedDate = new Date(dataServer.updated);

    const year = updatedDate.getFullYear();
    const month = String(updatedDate.getMonth() + 1).padStart(2, "0");
    const day = String(updatedDate.getDate()).padStart(2, "0");
    const hours = String(updatedDate.getHours()).padStart(2, "0");
    const minutes = String(updatedDate.getMinutes()).padStart(2, "0");

    const formattedDate = year + "-" + month + "-" + day + " " + hours + ":" + minutes;

    document .getElementById("updatedTime").textContent = T.serverDataUpdated + formattedDate;
  }catch(error){
    /*
     * Server appears offline or unreachable.
     */
    console.error("Could not load server data:", error);
    document.getElementById("statusDot").className = "status-dot offline";
    document.getElementById("serverStatus").textContent = T.serverStatusUnavailable;
    document.getElementById("playerList").innerHTML = '<span class="no-players">' + T.couldNotContact + '</span>';
  }
}

/*
 * Check if server data has been modified.
 */
let serverJsonLastModified = null;

async function checkServerData(){
  try{
    const response = await fetch(
      SERVER_JSON_URL + "?t=" + Date.now(), { method: "HEAD", cache: "no-store" } );

    if(!response.ok){
      throw new Error("HTTP error: " + response.status);
    }

    const lastModified = response.headers.get("Last-Modified");

    /*
     * First check: load the dataServer
     */
    if(serverJsonLastModified === null){
      serverJsonLastModified = lastModified;
      await loadServerData();
      return;
    }

    /*
     * Only download the JSON if the file changed.
     */
    if(lastModified !== serverJsonLastModified){
      serverJsonLastModified = lastModified;
      await loadServerData();
    }

  }catch(error){
    console.error("Could not check server data:", error);
  }
}


/*
 * initialize all the functions
 */
async function initialize(){
  /*
   * Apply translations.
   */
  applyTranslations();

  /*
   * Load static data from JSON.
   */
  try{
    await loadStaticData();
  }catch(error){
    console.error("Could not load static server data:", error);
  }

  /*
   * Run check if Server Data is modified otherwise load immediately.
   */
  await checkServerData();

  /*
   * Refresh every 10 seconds if modified.
   */
  setInterval(checkServerData, 10000);
}

initialize();
